<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");


//Udalyaem pochtovie sobitita
	$et = new CEventType;
	$et->Delete("LOGICTIM_BONUS_FROM_ORDER_ADD");
	$et->Delete("LOGICTIM_BONUS_FROM_REFERAL_ADD");
	$et->Delete("LOGICTIM_BONUS_FROM_REGISTER_ADD");
	$et->Delete("LOGICTIM_BONUS_FROM_BIRTHDAY_ADD");
	$et->Delete("LOGICTIM_BONUS_FROM_FREE_ADD");
	$et->Delete("LOGICTIM_BONUS_WARNING_END_TIME");
	$et->Delete("LOGICTIM_BONUS_FROM_REPOST");
	$et->Delete("LOGICTIM_BONUS_FROM_REVIEW");
	$et->Delete("LOGICTIM_BONUS_FROM_LINK");
	$et->Delete("LOGICTIM_BONUS_FROM_SUBSCRIBE");
	$et->Delete("LOGICTIM_BONUS_EXIT_BONUS_CLOSE");
	$et->Delete("LOGICTIM_BONUS_EXIT_BONUS_CANCEL");
	$et->Delete("LOGICTIM_BONUS_EXIT_BONUS_INSERT");


//Udalyaem pochtovie shabloni
$rsMess = CEventMessage::GetList($by="site_id", $order="desc", array("TYPE_ID" => array("LOGICTIM_BONUS_FROM_ORDER_ADD", "LOGICTIM_BONUS_FROM_REFERAL_ADD", "LOGICTIM_BONUS_FROM_REGISTER_ADD", "LOGICTIM_BONUS_FROM_BIRTHDAY_ADD", "LOGICTIM_BONUS_FROM_FREE_ADD", "LOGICTIM_BONUS_WARNING_END_TIME", "LOGICTIM_BONUS_FROM_REPOST", "LOGICTIM_BONUS_FROM_REVIEW", "LOGICTIM_BONUS_FROM_LINK", "LOGICTIM_BONUS_FROM_SUBSCRIBE", "LOGICTIM_BONUS_EXIT_BONUS_CLOSE", "LOGICTIM_BONUS_EXIT_BONUS_CANCEL", "LOGICTIM_BONUS_EXIT_BONUS_INSERT")));
$arMessId = array();
while($MessTemp = $rsMess->Fetch())
{
	CEventMessage::Delete($MessTemp["ID"]);
}

	
?>